/** @type {import('tailwindcss').Config} */
import daisyui from "daisyui";
export default {
    purge: [
        "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
        "./storage/framework/views/*.php",
        "./resources/views/**/*.blade.php",
        "./resources/js/**/*.vue",
        "./resources/js/*/*.vue",
        "./node_modules/flowbite/**/*.js",
        "./app/Filament/**/*.php",
        "./resources/views/filament/**/*.blade.php",
        "./vendor/filament/**/*.blade.php",
    ],
    darkMode: "class",
    content: [
        "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
        "./storage/framework/views/*.php",
        "./resources/views/**/*.blade.php",
        "./resources/js/**/*.vue",
        "./resources/js/*/*.vue",
        "./node_modules/flowbite/**/*.js",
        "./app/Filament/**/*.php",
        "./resources/views/filament/**/*.blade.php",
        "./vendor/filament/**/*.blade.php",
    ],
    theme: {
        extend: {
            colors: {
                gold: "#FBD0A0",
                yellow: "#FF9900",
                base: "#0e5b5c",
                secondary: "#959183",
            },          
             fontFamily: {
                exo: ['"Exo 2"', "sans-serif"],
                outfit: ['"Outfit"', "sans-serif"],
                custom: [
                    '"Trebuchet MS"',
                    '"Lucida Sans Unicode"',
                    '"Lucida Grande"',
                    '"Lucida Sans"',
                    "Arial",
                    "sans-serif",
                ],
            },
        },
    },
     safelist: [
        "bg-gradient-to-r",
        "from-sky-400",
        "to-sky-600",
        "from-base",
        "to-teal-600",
        "from-lime-400",
        "to-lime-600",
        "from-cyan-600",
        "to-cyan-800",
        "from-emerald-400",
        "to-emerald-600",
        "font-mono",
        "font-serif",
        "font-elegant",
        "font-classic",
        "font-sans",
        "font-exo",
        "font-custom",
        "font-outfit",
        "ring-cyan-500",
        "ring-sky-500",
        "ring-emerald-500",
        "ring-lime-500",
        "bg-black",
        "text-gold",
        "ring-gold",
    ],
    plugins: [require("daisyui")],
    darkMode: "class",
    daisyui: {
        darkTheme: true,
    },
};
